#-------------------------------------------------------------------------------
# A plotting script to plot the algorithm results for the Roblox Take Home Test
# Note that this script is entirely AI written, with just edits and feedback
# from the human author.
#-------------------------------------------------------------------------------

import pandas as pd
import matplotlib.pyplot as plt

# Read the timing data generated by AlgorithmsTest.cpp.
data = pd.read_csv("algorithm_timings.csv")

# Rename the implementation labels for the plot.
algorithm_names = {
    "optimized": "Bespoke",
    "standard": "Standard",
    "predictive": "Predictive",
}

data["algorithm"] = data["algorithm"].map(algorithm_names)

# Convert nanoseconds to milliseconds for a more readable y-axis.
data["time_ms"] = data["time_ns"] / 1_000_000.0

# Plot one line for each algorithm.
for algorithm_name, algorithm_data in data.groupby("algorithm"):
    algorithm_data = algorithm_data.sort_values("n")

    plt.plot(
        algorithm_data["n"],
        algorithm_data["time_ms"],
        marker="o",
        markersize=3,
        label=algorithm_name,
    )

# Both the input size and execution time span large ranges, so logarithmic axes
# make the relative scaling of the algorithms easier to compare.
plt.xscale("log")
plt.yscale("log")

plt.xlabel("Sequence position, n")
plt.ylabel("Execution time (ms)")
plt.title("Sequence Generation Algorithm Timing")
plt.legend()
plt.grid(True, which="both", linestyle="--", linewidth=0.5)
plt.tight_layout()

plt.savefig("algorithm_timings.png", dpi=300)
plt.show()