//------------------------------------------------------------------------------
// The header file to define the functions for the Roblox Take Home Test
//
// The problem is to generate the nth number in a sequence, where the sequence
// is defined as being the ordered set of numbers that can be formed by
// combining factors of 2,3, and 5. The sequence starts with 1, and the next
// numbers are generated by multiplying the previous numbers by 2, 3, or 5. No
// other factors are allowed. The sequence is ordered in ascending order, and
// duplicates are not allowed.
//
// The solutions naiveNumberGeneration and optimizedNumberGeneration are two
// original functions and algorithms that are entirely my own work, and are not
// copied from any other source. The standardNumberGeneration function is a
// well-known algorithm that I find via research and implemented. The
// predictiveNumberGeneration function is an algorithm I found and refined with
// the help of AI. This would have been very difficult to do myself under the
// time constraints.
//
// Author: Sundeep Singh
// Date: July 26, 2026
//-------------------------------------------------------------------------------
#pragma once

#include <cmath>    // for std::log
#include <cstdint>  // for uint64_t

namespace Roblox {

/// <summary>
/// This function generates the nth number in the desired sequence of numbers by
/// taking a very naive approach and just checking each number and verifying
/// that it is valid. This will check a lot of unnecessary numbers, and is not
/// ideal for large n, but a good starting point.
/// </summary>
/// <param name="n">The position in the sequence to generate.</param>
/// <returns>The nth number in the sequence.</returns>
uint64_t naiveNumberGeneration(uint64_t n);

/// <summary>
/// A struct to hold a triplet of numbers, which represent the powers of 2, 3,
/// and 5.
/// This also stores the log of the number, as that is a much smaller number,
/// easier to compute with the power representation, and allows us to compare
/// values without having to compute the actual number, which can be very large.
/// </summary>
struct Triplet {
  Triplet(const uint64_t a, const uint64_t b, const uint64_t c)
      : alpha(a),
        beta(b),
        gamma(c),
        logValue(a * std::log(2) + b * std::log(3) + c * std::log(5)) {}

  /// <summary>
  /// Compare the floating point log of this number to another triplet's log
  /// value.
  /// </summary>
  /// <param name="other">The other triplet to be compared to.</param>
  /// <returns>True if this number is less than the other number.</returns>
  bool operator<(const Triplet& other) const {
    return logValue < other.logValue;
  }

  /// <summary>
  /// Compare to see if two triplets are equal.
  /// Note this does not check the log representation as it is subject to
  /// floating point error. The triplet values are an exact representation and
  /// can be compared exactly.
  /// </summary>
  /// <param name="other"> The other triplet to compare to.</param>
  /// <returns> True if the numbers are the same.</returns>
  bool operator==(const Triplet& other) const {
    return alpha == other.alpha && beta == other.beta && gamma == other.gamma;
  }

  uint64_t alpha;
  uint64_t beta;
  uint64_t gamma;
  long double logValue;
};

/// <summary>
/// This function generates the nth number in the desired sequence of numbers by
/// generating the numbers in the sequence directly by varying powers of the
/// factors. This will overgenerate some value in order to guarantee
/// completeness of the set
/// <param name="n">Which entry in the sequence to generate</param>
/// <returns>A triplet representing the nth value in the sequence</returns>
Triplet optimizedNumberGeneration(uint64_t n);

/// <summary>
/// This function generates the nth number in the desired sequence of numbers by
/// using the standard method of solving this problem, which is to use three
/// pointers to track the next number in the sequence. This is a more efficient
/// approach than either of the other approaches, as it generates the sorted
/// list exactly as it goes with no overshooting.
/// </summary>
/// <param name="n">Which entry in the sequence to generate</param>
/// <returns>A triplet representing the nth value in the sequence</returns>
Triplet standardNumberGeneration(uint64_t n);

/// <summary>
/// This function generates the nth number in the desired sequence of numbers by
/// predicting the log value of the nth value, generating a thin shell of values
/// around that log value, and then generating the triplet values in that shell.
/// </summary>
/// <param name="n">Which entry in the sequence to generate</param>
/// <returns>A triplet representing the nth value in the sequence</returns>
Triplet predictiveNumberGeneration(uint64_t n);

}  // namespace Roblox
